Global:
  use_gpu: True
  epoch_num: 500 #72
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/rec/fpn50_srn_2_4_baseline
  save_epoch_step: 10
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 5000]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints:
  save_inference_dir:
  use_visualdl: True     #可视化开关
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/ppocr_keys_v2.txt
  character_type: ch
  max_text_length: 25
  num_heads: 8
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_srn.txt
  count_model: True


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
#  Backbone:
#    name: MobileNetV3
#    scale: 0.5
#    model_name: large
  Backbone:
    name: ResNetFPN
#  Backbone:
#    name: MobileNetV3
#    scale: 0.5
#    model_name: small
#    small_stride: [1, 2, 2, 2]
#  Neck:
#    name: SequenceEncoder
#    encoder_type: cnn
#    hidden_size: 128
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
#    name: LMDBDataSet
#    data_dir: ./train_data/data_lmdb_release/training/
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list: ["./train_data/ppdataset/train/labeltrain.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32,320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: False
    batch_size_per_card: 82
    drop_last: False
    num_workers: 4

Eval:
  dataset:
#    name: LMDBDataSet
#    data_dir: ./train_data/data_lmdb_release/validation/
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list: ["./train_data/ppdataset/train/labelval.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3,32,320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 82
    num_workers: 4
